@@ -0,0 +1,92 @@
CREATE DATABASE vk;

USE vk;

CREATE TABLE configuration (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  password VARCHAR(50) NOT NULL UNIQUE,
  language VARCHAR(50) NOT NULL,
  verification BOOLEAN,
  url_adress VARCHAR(150) NOT NULL UNIQUE,
  visible_id TINYINT UNSIGNED NOT NULL
);

CREATE TABLE visibility (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  vis VARCHAR(255) NOT NULL
);

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  telephone VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  gender CHAR(1) NOT NULL, 
  birthday DATE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE address (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
city_id INT
country_id INT
);

CREATE TABLE profiles (
  user_id INT UNSIGNED NOT NULL PRIMARY KEY,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE profiles ADD photo_id INT UNSIGNED AFTER user_id;

CREATE TABLE messages (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
from_user_id INT UNSIGNED NOT NULL,
to_user_id INT UNSIGNED NOT NULL,
body TEXT NOT NULL,
is_important BOOLEAN,
is_delivered BOOLEAN,
created_at DATETIME DEFAULT NOW()
);

CREATE TABLE friendship (
  user_id INT UNSIGNED NOT NULL,
  friend_id INT UNSIGNED NOT NULL,
  status_id INT UNSIGNED NOT NULL,
  requested_at DATETIME DEFAULT NOW(),
  confirmed_at DATETIME,
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE communities_links (
  community_id INT UNSIGNED NOT NULL,
  link VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE communities_users (
community_id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,
PRIMARY KEY (community_id, user_id)
)

CREATE TABLE users_links (
  user_id INT UNSIGNED NOT NULL,
  link VARCHAR(150) NOT NULL UNIQUE
);


CREATE TABLE media (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
filename VARCHAR(255) NOT NULL,
size INT NOT NULL,
metadata JSON,
media_type_id INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE media_types (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE
);